// Build step — generate the `Manifest` TypeScript type from the vendored schema
// (json-schema-to-typescript). This is the build-time contract type exported by
// @tommy/manifest for @tommy/sdk and the loader (spec Phase 3 change (a) / ac5).
// It is DISTINCT from `tommy manifest typegen`, which emits per-MP contract types.

import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const schemaPath = fileURLToPath(new URL('../src/schema/manifest-schema.json', import.meta.url));
const outDir = fileURLToPath(new URL('../src/generated/', import.meta.url));

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

const banner = `/* eslint-disable */
// Generated by @tommy/manifest (scripts/generate-types.mjs) from
// src/schema/manifest-schema.json — DO NOT EDIT. Run \`yarn typegen\` to refresh.`;

const ts = await compile(schema, 'Manifest', {
  bannerComment: banner,
  additionalProperties: true,
  declareExternallyReferenced: true,
  format: false,
  unreachableDefinitions: true,
});

mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, 'manifest.ts');
writeFileSync(outPath, ts, 'utf8');
console.log(`✔ wrote ${outPath} (${ts.split('\n').length} lines)`);
