---
title: "Nurse Provider"
package: "nurse_provider"
version: "1.0.0"
summary: "Nurse Provider"
description: "This addon provides nurse provider integration and actions."
developer: "Tommy Labs GmbH"
homepage: "https://mytommy.com"
private: false
default_order_parameters: &default_order_parameters
  id:
    title: "Order ID"
    type: "integer"
    required: true
  assignee_id:
    title: "Assignee ID"
    type: "integer"
    required: true
  assignee_team_id:
    title: "Assignee Team ID"
    type: "integer"
    required: true
  event_id:
    title: "Event ID"
    type: "integer"
    required: true
  status:
    title: "Order status"
    type: "string"
    required: true
  canceled:
    title: "Order canceled"
    type: "boolean"
    required: true
  qa_hold:
    title: "QA hold flag"
    type: "boolean"
    required: true
triggers:
  order_canceled:
    title: "Order canceled"
    observe:
      object: Vendor::Order
      event: cancel
      conditions:
        canceled: true
    parameters:
      <<: *default_order_parameters
  order_status_changed:
    title: "Order status changed"
    observe:
      object: Vendor::Order
      event: status_change
    parameters:
      <<: *default_order_parameters
tasks:
  mark_orders_completed_after_24h:
    title: "Mark QA orders as completed after 24h"
    summary: "Mark QA orders as completed after 24h if not under QA hold."
    execute: "Task::NurseProvider::MarkQaOrdersCompleted"
# conditions:
#   temperature:
#     title: "Weather Temperature"
#     summary: "Weather temperature is"
#     execute: "conditions/temperature.js"
#     options:
#       <<: *default_options
#       temperature:
#         title: "Temperature"
#         type: "integer"
#         unit: "degree"
#         required: true
#         default:
#           operator: "greater_than"
#           value: 20
actions:
  notify_nurse_on_booking_paid:
    title: "Notify nurse on booking confirmed"
    summary: "Notify nurse when a new booking is confirmed."
    trigger:
      package: nurse_provider
      name: order_status_changed
    conditions:
      -
        package: tommy
        name: trigger_data_matcher
        options:
          status:
            operator: equals
            value: paid
    activity:
      package: chat
      name: send_message
    options:
      target_user_parameter: assignee_id
    mappings:
      message:
        title: "Message text"
        type: "string"
        value: "You have a new booking. See Bookings for more details."
    default: true
  notify_nurse_on_booking_canceled:
    title: "Notify nurse on booking canceled"
    summary: "Notify nurse when an existing booking is canceled."
    trigger:
      package: nurse_provider
      name: order_canceled
    activity:
      package: chat
      name: send_message
    options:
      target_user_parameter: assignee_id
    mappings:
      message:
        title: "Message text"
        type: "string"
        value: "One of your bookings have been cancelled. Please see Bookings for details."
  mark_orders_completed_after_24h:
    title: "Mark QA orders as completed after 24h"
    summary: "Mark QA orders as completed after 24h if not under QA hold."
    task:
      package: nurse_provider
      name: mark_orders_completed_after_24h
    schedule:
      cron: "0 9 * * *"
    default: true
  credit_nurse_on_order_complete:
    title: "Credit nurse on order complete"
    summary: "Credit nurse on order complete."
    trigger:
      package: nurse_provider
      name: order_status_changed
    activity:
      package: nurse_provider
      name: pay_nurse_on_order_complete
    options:
      target_user_parameter: assignee_id
    default: true
activities:
  # mark_qa_orders_completed:
  #   title: "Mark QA orders completed"
  #   description: "Mark QA orders completed."
  #   execute: "Activity::NurseProvider::MarkQaOrdersCompleted"
  pay_nurse_on_order_complete:
    title: "Pay nurse on order complete"
    description: "Pay nurse on order complete."
    execute: "Activity::NurseProvider::PayNurseOnOrderComplete"
views:
  index:
    title: "Home Service"
    type: "page"
    index: true
    framed: false
    path: "/nurse_booking/"
