title: Credentials
package: "credentials"
summary: "Manage connected thrid party accounts."
description: "Manage connected thrid party and social media accounts"
version: "1.0.0"
developer: "Tommy Labs GmbH"
homepage: "https://mytommy.com"
private: false
locales:
  - en-US
  - zh-CN
roles:
  - Team Admin
permissions:
  addon_access:
    title: "Allow Team Member Access"
    hint: "Select Team Members who can access this Add-on"
    default_roles:
      - Team Admin
    operations:
      - read
assets:
  -
    type: "stylesheet"
    file: "build/addon.css"
  -
    type: "javascript"
    file: "build/addon.js"
views:
  index:
    title: Credentials
    index: true
    path: "/credentials/"
    type: "page"
