// `tommy manifest typegen` — emit <id>.contracts.d.ts so an MP author gets
// autocomplete on THEIR OWN triggers/conditions/activities, derived from the
// embedded payload/input/result JSON Schemas (README §Type generation).

import { compile } from 'json-schema-to-typescript';
import { parseManifest } from './parse.js';

function pascal(id) {
  const name = String(id)
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
  // Guarantee a valid TS identifier prefix even for pathological ids (empty or
  // digit-leading) — schema-valid ids start with a letter, but typegen does not
  // pre-validate its input.
  return !name || /^[0-9]/.test(name) ? `Mp${name}` : name;
}

const JSTT_OPTS = {
  bannerComment: '',
  additionalProperties: false,
  declareExternallyReferenced: true,
  format: false,
};

function groupSchema(title, properties) {
  return {
    title,
    type: 'object',
    additionalProperties: false,
    required: Object.keys(properties),
    properties,
  };
}

/**
 * Generate a `.d.ts` string for a parsed manifest object.
 * @returns {Promise<string>}
 */
export async function typegenFromManifest(data) {
  const Name = pascal(data.id ?? 'mini-program');
  const chunks = [];

  const triggers = data.triggers ?? {};
  const triggerProps = {};
  for (const [name, t] of Object.entries(triggers)) {
    if (t?.payloadSchema) triggerProps[name] = t.payloadSchema;
  }
  if (Object.keys(triggerProps).length) {
    chunks.push(await compile(groupSchema(`${Name}Triggers`, triggerProps), `${Name}Triggers`, JSTT_OPTS));
  }

  const conditions = data.conditions ?? {};
  const conditionProps = {};
  for (const [name, c] of Object.entries(conditions)) {
    conditionProps[name] = {
      type: 'object',
      additionalProperties: false,
      properties: {
        input: c?.inputSchema ?? { type: 'object' },
        result: c?.returnSchema ?? { type: 'object' },
      },
    };
  }
  if (Object.keys(conditionProps).length) {
    chunks.push(await compile(groupSchema(`${Name}Conditions`, conditionProps), `${Name}Conditions`, JSTT_OPTS));
  }

  const activities = data.activities ?? {};
  const activityProps = {};
  for (const [name, a] of Object.entries(activities)) {
    activityProps[name] = {
      type: 'object',
      additionalProperties: false,
      properties: {
        input: a?.inputSchema ?? { type: 'object' },
        result: a?.resultSchema ?? { type: 'object' },
      },
    };
  }
  if (Object.keys(activityProps).length) {
    chunks.push(await compile(groupSchema(`${Name}Activities`, activityProps), `${Name}Activities`, JSTT_OPTS));
  }

  const actionIds = Object.keys(data.actions ?? {});
  if (actionIds.length) {
    chunks.push(`export type ${Name}ActionId = ${actionIds.map((a) => `'${a}'`).join(' | ')};\n`);
  }

  const banner = `// ${data.id ?? 'mini-program'}.contracts.d.ts — generated by @tommy/manifest, do not edit\n\n`;
  return banner + chunks.join('\n');
}

/** Convenience: generate types straight from manifest source text. */
export async function typegenFromSource(source) {
  const { data, yamlErrors } = parseManifest(source);
  if (yamlErrors.length) {
    const e = new Error(`manifest is not valid YAML: ${yamlErrors[0].message}`);
    e.code = 'EYAML';
    throw e;
  }
  return typegenFromManifest(data);
}
